config/routes.rb
Rails.application.routes.draw do
  root 'containers#index'

  resources :containers, only: [:index] do
    collection do
      get :search
    end
  end

  namespace :dashboard do
    resources :vegetables, only: [:index, :create, :edit, :update, :destroy]
    resources :companies, only: [:index, :create, :edit, :update, :destroy]
  end
end

app/models/dashboard/company.rb
module Dashboard
  # rubocop:disable Rails/InverseOf
  # rubocop:disable Layout/LineLength
  class Company < ApplicationRecord
    has_many :from_rfid_containers, class_name: 'RfidContainer', foreign_key: 'from_place', dependent: :restrict_with_error
    has_many :to_rfid_containers, class_name: 'RfidContainer', foreign_key: 'to_place', dependent: :restrict_with_error
    validates :company_id, length: { minimum: 1 }, uniqueness: true
    validates :company_name, length: { minimum: 1 }
  end
  # rubocop:enable Rails/InverseOf
  # rubocop:enable Layout/LineLength
end

app/models/dashboard/vegetable.rb
module Dashboard
  # rubocop:disable Rails/InverseOf
  class Vegetable < ApplicationRecord
    has_many :rfid_containers, foreign_key: :contents, dependent: :restrict_with_error
    validates :vegetable_id, length: { minimum: 1 }, uniqueness: true
    validates :vegetable_name, length: { minimum: 1 }
  end
  # rubocop:enable Rails/InverseOf
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  layout 'dashboard'
end

app/controllers/dashboard/companies_controller.rb
module Dashboard
  class CompaniesController < Dashboard::BaseController
    def index
      @companies = Company.all
      @form = Company.new
    end

    def create
      @company = Company.new(company_id: input_params[:company_id],
                             company_name: input_params[:company_name])

      @company.save
      @companies = Company.all
    end

    def edit
      @company = Company.find_by(company_id: input_params[:id])
    end

    def update
      @company = Company.find_by(company_id: input_params[:id])

      @company.company_name = input_params[:company_name]
      @company.save
      @companies = Company.all
    end

    def destroy
      @company = Company.find_by(company_id: input_params[:id])

      @company.destroy
      @companies = Company.all
    end

    private

    def input_params
      params.permit(:company_id, :company_name, :id)
    end
  end
end

app/controllers/dashboard/vegetables_controller.rb
module Dashboard
  class VegetablesController < Dashboard::BaseController
    def index
      @vegetables = Vegetable.all
      @form = Vegetable.new
    end

    def create
      @vegetable = Vegetable.new(vegetable_id: input_params[:vegetable_id],
                                 vegetable_name: input_params[:vegetable_name])

      @vegetable.save
      @vegetables = Vegetable.all
    end

    def edit
      @vegetable = Vegetable.find_by(vegetable_id: input_params[:id])
    end

    def update
      @vegetable = Vegetable.find_by(vegetable_id: input_params[:id])

      @vegetable.vegetable_name = input_params[:vegetable_name]
      @vegetable.save
      @vegetables = Vegetable.all
    end

    def destroy
      @vegetable = Vegetable.find_by(vegetable_id: input_params[:id])

      @vegetable.destroy
      @vegetables = Vegetable.all
    end

    private

    def input_params
      params.permit(:vegetable_id, :vegetable_name, :id)
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/dashboard/companies/_company_edit.html.erb
<td><%= company.company_id %></td>
<td>
  <%= form_with(url: dashboard_company_path(id: company.company_id), method: :put, remote: true) do |f| %>
    <%= f.hidden_field :company_id, :value => company.company_id %>
    <%= f.text_field :company_name, :value => company.company_name %>
    <%= f.submit :更新 %>
  <% end %>
</td>

app/views/dashboard/companies/_company_table.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>企業ID</th>
        <th>企業名</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% companies.each do |company| %>
        <tr id="company_<%= company.company_id %>" >
          <td><%= company.company_id %></td>
          <td><%= company.company_name %></td>
          <td>
            <%= link_to '編集', edit_dashboard_company_path(id: company.company_id), method: :get, remote: true %>
          </td>
          <td>
            <%= link_to '削除', dashboard_company_path(id: company.company_id), method: :delete,
                data: { confirm: "本当に削除してもよろしいですか？", cancel: 'やめる', commit: '削除する'}, remote: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/companies/_error.html.erb
<% if company.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/dashboard/companies/create.js.erb
$('#company_area').html("<%= escape_javascript(render 'company_table', companies: @companies) %>");
$('#validation_area').html("<%= j(render 'error', { company: @company }) %>");

app/views/dashboard/companies/destroy.js.erb
$('#company_area').html("<%= escape_javascript(render 'company_table', companies: @companies) %>");
$('#validation_area').html("<%= j(render 'error', { company: @company }) %>");

app/views/dashboard/companies/edit.js.erb
$('#company_<%= @company.company_id %>').html("<%= escape_javascript(render 'company_edit', company: @company) %>");

app/views/dashboard/companies/index.html.erb
<div id="validation_area"></div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><i class="fa fa-database"></i> 企業追加</h3>
  </div>
  <%= form_with(url: dashboard_companies_path, method: :post, remote: true) do |f| %>
    <table class="table">
      <thead>
        <tr>
          <th>企業ID</th>
          <th>企業名</th>
        </tr>
      </thead>
      <tbody class="bulk-registration-form">
        <tr class="item">
          <td>
            <%= f.text_field :company_id, class: 'form-control' %>
          </td>
          <td>
            <%= f.text_field :company_name, class: 'form-control' %>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="text-center submit-area">
      <%= f.submit '追加', class: 'btn btn-success' %>
    </div> 
  <% end %>
</div>

<h3>企業一覧</h3>
<div id="company_area">
  <%= render "company_table", companies: @companies %>
</div>

app/views/dashboard/companies/update.js.erb
$('#company_area').html("<%= escape_javascript(render 'company_table', companies: @companies) %>");
$('#validation_area').html("<%= j(render 'error', { company: @company }) %>");