config/routes.rb
Rails.application.routes.draw do
  root 'containers#index'

  resources :containers, only: [:index] do
    collection do
      get :search
    end
  end

  namespace :dashboard do
    resources :vegetables, only: [:index, :create, :edit, :update, :destroy]
    resources :companies, only: [:index, :create, :edit, :update, :destroy]
  end
end

app/controllers/containers_controller.rb
require 'search_form'

class ContainersController < ApplicationController
  def index
    @search_params = {}
    @flg_params = SearchForm.new
    @containers_daily = RfidContainer.new
    @containers_monthly = RfidContainer.new
  end

  def search
    @search_params = input_params
    @flg_params = SearchForm.new(nippo_flg: @search_params[:nippo_flg], geppo_flg: @search_params[:geppo_flg])
    @flg_params.flg_check
    @containers_daily = RfidContainer.search_daily(@search_params).decorate if @search_params[:nippo_flg]
    @containers_monthly = RfidContainer.search_monthly(@search_params).decorate if @search_params[:geppo_flg]
  end

  private

  def input_params
    params.fetch(:container, {}).permit(
      :nippo_flg,
      :geppo_flg,
      :daily,
      :monthly,
      :entering_flg,
      :container_id,
      :entering_date,
      :leaving_date,
      :contents,
      :contents_size,
      :from_place,
      :to_place
    )
  end
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/views/containers/_search_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><i class="fa fa-search"></i> 検索条件</h3>
  </div>
  <div class="panel-body">
    <% if @flg_params.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <ul>
          <% @flg_params.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row necessary-input">
      <div class="col-sm-3">
        <div class="form-group">
          <div class="checkbox">
            <label>
              <%= f.check_box :nippo_flg, checked: @search_params[:nippo_flg] == '1' %>
              日報
            </label>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-5 control-label" for="">日付</label>
          <div class="col-sm-7">
            <%= f.text_field :daily, class: 'form-control nippo-label', autocomplete: "off", value: @search_params[:daily] %>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="form-group">
          <div class="checkbox">
            <label>
              <%= f.check_box :geppo_flg, checked: @search_params[:geppo_flg] == '1' %>
              月報
            </label>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-4 control-label" for="">年月</label>
          <div class="col-sm-7">
            <%= f.text_field :monthly, class: 'form-control', :placeholder => "1990-01", value: @search_params[:monthly] %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-3">
        <div class="form-group">
          <label class="col-sm-5 control-label" for="">入出庫状況</label>
          <div class="col-sm-7">
            <%= f.select :entering_flg, {'入庫中': 1, '出庫済': 0}, { include_blank: true, selected: @search_params[:entering_flg]}, {class: 'form-control'} %>
          </div>
        </div>
        
        <div class="form-group">
          <label class="col-sm-5 control-label" for="">コンテナ番号</label>
          <div class="col-sm-7">
            <%= f.text_field :container_id, class: 'form-control', autocomplete: "off", value: @search_params[:container_id] %>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="form-group">
          <label class="col-sm-4 control-label" for="">入庫日時</label>
          <div class="col-sm-7">
            <%= f.text_field :entering_date, class: 'form-control entering-label', autocomplete: "off", value: @search_params[:entering_date] %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-4 control-label" for="">出庫日時</label>
          <div class="col-sm-7">
            <%= f.text_field :leaving_date, class: 'form-control leaving-label', autocomplete: "off", value: @search_params[:leaving_date] %>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="form-group">
          <label class="col-sm-3 control-label" for="">入荷元</label>
          <div class="col-sm-8">
            <%= f.collection_select :from_place, Dashboard::Company.all, :company_id, :company_name, {:include_blank => true, selected: @search_params[:from_place]}, {class: 'form-control'} %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-3 control-label" for="">出荷先</label>
          <div class="col-sm-8">
            <%= f.collection_select :to_place, Dashboard::Company.all, :company_id, :company_name, {:include_blank => true, selected: @search_params[:to_place]}, {class: 'form-control'} %>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="form-group">
          <label class="col-sm-4 control-label" for="">野菜の種類</label>
          <div class="col-sm-8">
            <%= f.collection_select :contents, Dashboard::Vegetable.all, :vegetable_id, :vegetable_name, {:include_blank => true, selected: @search_params[:contents]}, {class: 'form-control'} %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-4 control-label" for="">サイズ</label>
          <div class="col-sm-8">
            <%= f.select :contents_size, {'S': '00000001', 'M': '00000002', 'L': '00000003'}, {include_blank: true, selected: @search_params[:contents_size]}, {class: 'form-control'} %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-12 row text-center">
      <button class="btn btn-default btn-left clear-form" type="button">クリア</button>
      <button class="btn btn-default btn-success" type="submit"><i class="fa fa-search"></i> 検索</button>
    </div>
  </div>
</div>

app/views/containers/index.html.erb
<%= javascript_include_tag "containers.js" %>
<% content_for(:title) do %>
  在庫照会
<% end %>

<%= form_with scope: :container, url: search_containers_path, method: :get, local: true  do |f| %>
  <%= render 'search_form', f: f %>
<% end %>

app/views/containers/search.html.erb
<% content_for(:title) do %>
  在庫照会
<% end %>

<%= form_with scope: :container, url: search_containers_path, method: :get, local: true  do |f| %>
  <%= render 'search_form', f: f %>
<% end %>
<div class="search_result_area">
  <div class="col-sm-6 search_result_area_daily">
    <h3>日報</h3>
    <table class="table table-list sort-table">
      <thead>
        <tr>
          <th>状況</th>
          <th>コンテナ番号</th>
          <th>入庫日時</th>
          <th>出庫日時</th>
          <th>野菜の種類</th>
          <th>サイズ</th>
          <th>入荷元</th>
          <th>出荷先</th>
        </tr>
      </thead>
      <tbody>
        <% if @search_params[:nippo_flg] != '1' || @containers_daily.nil? %>
        <% else %>
          <% @containers_daily.each do |container| %>
            <tr>
              <td><%= container.entering_condition %></td>
              <td><%= container.container_id %></td>
              <td><%= container.entering_date %></td>
              <td><%= container.leaving_date %></td>
              <td><%= container.vegetable_name %></td>
              <td><%= container.contents_size_for_display %></td>
              <td><%= container.fp_name %></td>
              <td><%= container.tp_name %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-sm-6 search_result_area_monthly">
    <h3>月報</h3>
    <table class="table table-list sort-table">
      <thead>
        <tr>
          <th>状況</th>
          <th>コンテナ番号</th>
          <th>入庫日時</th>
          <th>出庫日時</th>
          <th>野菜の種類</th>
          <th>サイズ</th>
          <th>入荷元</th>
          <th>出荷先</th>
        </tr>
      </thead>
      <tbody>
        <% if @search_params[:geppo_flg] != '1' ||@containers_monthly.nil? %>
        <% else %>
          <% @containers_monthly.each do |container| %>
            <tr>
              <td><%= container.entering_condition %></td>
              <td><%= container.container_id %></td>
              <td><%= container.entering_date %></td>
              <td><%= container.leaving_date %></td>
              <td><%= container.vegetable_name %></td>
              <td><%= container.contents_size_for_display %></td>
              <td><%= container.fp_name %></td>
              <td><%= container.tp_name %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>